server:
  port: 9001
spring:
  datasource:
    url: jdbc:h2:mem:Department;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: departmentservice

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true

### This is now coming from spring cloud via bootstrap yaml
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8762/eureka/
#  instance:
#    hostname: localhost
resilience4j:
  circuitbreaker:
    instances:
      findDepartmentById:
        register-health-indicator: true
